#! /bin/sh
### BEGIN INIT INFO
# Provides:          rserve
# Required-Start:  
# Required-Stop:
# Default-Start:  2 3 4 5
# Default-Stop:   
# Short-Description: Executes the rserve in daemon mode
# Description:
### END INIT INFO

## Config
# Default user:
USR="rserve"

start() {
	echo -n "Starting Rserve... "

	su - ${USR} -c "R --vanilla <<EOF
	library(Rserve)
	Rserve(args=\"--no-save\")
	EOF" > /dev/null

	$0 status
}

status() {
local GREEN="\033[0;32m"
local RED="\033[0;31m"
local NO_COLOUR="\033[0m"

	N=`ps -ef | grep Rserve | wc -l`
	if [ "$N" -lt 2 ]; then
		echo "Rserve is ${RED}down${NO_COLOUR}.";
	else
		echo "Rserve is ${GREEN}up${NO_COLOUR}.";
	fi
}

stop() {
	echo -n "Shutting down Rserve... "

	killall -9 Rserve

	$0 status
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status
	;;	
  restart|reload|force-reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 start|stop|status|restart" >&2
	exit 3
	;;
esac

:
